plugins:
  - import 

env:
  es2021: true
  node: true
extends:
  - 'airbnb-base'
  - 'plugin: import/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: off
  object-curly-newline: always
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [error, { 'allow': ['__filename', '__dirname'] }]
  import/no-named-as-default: off
  import/no-named-as-default-member: off
  import/no-extraneous-dependencies: off


